// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt8tOAndUQ4jM232wqz0kODjqVU6RS11E',
    appId: '1:1098428717556:android:a0fed38356efbd948041a1',
    messagingSenderId: '1098428717556',
    projectId: 'digital-health-app-a7157',
    databaseURL: 'https://digital-health-app-a7157-default-rtdb.firebaseio.com',
    storageBucket: 'digital-health-app-a7157.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK369Ue--ImtLqxdT8hQQvlfqakI-HpJM',
    appId: '1:1098428717556:ios:0f6a285f86c6ea998041a1',
    messagingSenderId: '1098428717556',
    projectId: 'digital-health-app-a7157',
    databaseURL: 'https://digital-health-app-a7157-default-rtdb.firebaseio.com',
    storageBucket: 'digital-health-app-a7157.firebasestorage.app',
    iosBundleId: 'com.digitalhealth.app',
  );
}
